arch: linear
aug: true
augmentation: RandomResizedCrop
batch_size: 512
ckpt: ''
ckpt_iter: -1
config_file: null
data: imagenet
dist: dp
dist_address: ''
encode_layer: h
encoder_ckpt: ''
eval_freq: 254
finetune: false
iters: 50782
log_freq: 254
lr: 0.5
lr_schedule: linear
model_id: -1
name: eval_imagenet-100_newmodels
node_rank: 0
opt: sgd
precompute_emb_bs: -1
problem: eval
save_freq: 10000000000000000
scale_lower: 0.08
seed: -1
test_bs: 512
tmp: false
warmup: 0.0
weight_decay: 0.0001
workers: 40
world_size: 1